name: get-secretmanager-secrets compile check
on:
  push:
    paths:
    - 'get-secretmanager-secrets/**'
  pull_request:
    paths:
    - 'get-secretmanager-secrets/**'

jobs:
  run:
    name: get-secretmanager-secrets compile check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: utils/compile-check.sh get-secretmanager-secrets
